[connections.sql]
server = "sql-mhp-sandbox.database.windows.net"
host = "sql-mhp-sandbox.database.windows.net"
database = "AdventureWorks2022"
username = "fabriclabs"
password = "Password123"
dialect = "mssql"

[connections.aw_db]
server = "sql-mhp-sandbox.database.windows.net"
host = "sql-mhp-sandbox.database.windows.net"
database = "AdventureWorks2022"
username = "fabriclabs"
password = "Password123"
dialect = "mssql"